//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.23 at 06:35:36 PM IST 
//


package com.vivek.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "email",
    "phone",
    "address"
})
@XmlRootElement(name = "Student")
public class Student {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Phone", required = true)
    protected String phone;
    @XmlElement(name = "Address", required = true)
    protected String address;
   

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    
    public String getEmail() {
        return email;
    }

    
    public void setEmail(String value) {
        this.email = value;
    }

    
    public String getPhone() {
        return phone;
    }

    
    public void setPhone(String value) {
        this.phone = value;
    }

   
    public String getAddress() {
        return address;
    }

   
    public void setAddress(String value) {
        this.address = value;
    }

}
